# Generated by Django 4.2.7 on 2023-12-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlateName', models.CharField(max_length=50)),
                ('Ingredients', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SensorId', models.BigIntegerField()),
                ('OwnerId', models.BigIntegerField()),
                ('type', models.BigIntegerField()),
                ('payload', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='Event',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
