# Generated by Django 4.2.7 on 2023-12-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localviewer', '0003_plates_rename_ingredients_fridge_ingredientname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='id',
        ),
        migrations.AlterField(
            model_name='sensors',
            name='SensorId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
