# Generated by Django 4.2.7 on 2023-12-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localviewer', '0004_remove_sensors_id_alter_sensors_sensorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='payload',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='type',
            field=models.SmallIntegerField(),
        ),
    ]
